databases:
  - name: hiretaskup_db
    databaseName: hiretaskup
    user: hiretaskup

services:
  - type: web
    name: hiretaskup
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hiretaskup.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hiretaskup_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: .onrender.com
